---
AWSTemplateFormatVersion: 2010-09-09
Description:  VAEC managed Service Account IAM User

Parameters:
# -- Parameter Store
    pProjectShort:
        Type : AWS::SSM::Parameter::Value<String>
        Default: /vaec/tag/ProjectShort
        
Resources:

# Policy to allow project admins to manage service accounts in a limited way
  rServiceAccountCustom:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Roles:
        - adfs-project-administrators
      Description: Service Account customized policy
      Path: /vaec/
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowProjAdminCustom
            Effect: Allow
            Action:
              - iam:CreateAccessKey
              - iam:DeleteAccessKey
              - iam:ListAccessKeys
              - iam:UpdateAccessKey
              - iam:GetUserPolicy
              - iam:ListUserPolicies
              - iam:GetUser
            # Any additional users that require management will be added here
            Resource: 
              - !GetAtt rServiceAccount1.Arn
            # Below is how specific users can be granted access to manage service account.
            # A YAML list of windows account names for each user who manages the account with above permissions.
            # e.g. Eric.Oliver3@va.gov maps to VHASDCOLIVEE1
            # Note: The name should be IN ALL CAPS.
            Condition:
              ForAnyValue:StringLike:
                saml:sub:
                - '*VHASDCOLIVEE1'

# Create all additional service accounts below:
# Resource name should be rServiceAccount#

  rServiceAccount1:            
    Type: AWS::IAM::User
    Properties: 
      # Ensure all service account IAM Users have this Permission Boundary set
      PermissionsBoundary: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/vaec/project-admin
      # Username should be ProjectShort-service-account-#
      UserName: !Join [ "",[ !Ref pProjectShort, "-service-account-1"]]
      # You must also define the set of LEAST PRIVILEGE PERMISSIONS for the service account.
      Policies:
      - PolicyName: ServiceAccountPolicy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Sid: ServiceAccountPolicy
            Effect: Allow
            Action: # Service identifier
            Resource:
            # - ARN of the resource. 
      